const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvis', {
  getState: () => ipcRenderer.invoke('state:get'),
  copyText: value => ipcRenderer.invoke('clipboard:write', value),
  parse: (text, context = {}) => ipcRenderer.invoke('command:parse', { text, ...context }),
  dispatchRequest: (text, context = {}) => ipcRenderer.invoke('request:dispatch', { text, source: context.source || 'typed', ...context }),
  dispatchCapability: (capabilityId, parameters = {}, context = {}) => ipcRenderer.invoke('request:dispatch', { capabilityId, parameters, source: context.source || 'button', ...context }),
  execute: (text, confirmed = false, context = {}) => ipcRenderer.invoke('command:execute', { text, confirmed, ...context }),
  updatePreferences: patch => ipcRenderer.invoke('preferences:update', patch),
  add: (collection, item) => ipcRenderer.invoke('collection:add', { collection, item }),
  update: (collection, id, patch) => ipcRenderer.invoke('collection:update', { collection, id, patch }),
  remove: (collection, id) => ipcRenderer.invoke('collection:remove', { collection, id }),
  clearActivity: () => ipcRenderer.invoke('activity:clear'),
  openMemoryFile: () => ipcRenderer.invoke('memory:open-file'),
  chooseFolder: kind => ipcRenderer.invoke('dialog:choose-folder', kind),
  exportData: () => ipcRenderer.invoke('data:export'),
  importData: () => ipcRenderer.invoke('data:import'),
  timerControl: action => ipcRenderer.invoke('timer:control', action),
  cancelAction: () => ipcRenderer.invoke('action:cancel'),
  saveAIConnection: payload => ipcRenderer.invoke('connection:save-ai', payload),
  saveAIWaterfall: payload => ipcRenderer.invoke('connection:save-ai-waterfall', payload),
  saveAICredentials: payload => ipcRenderer.invoke('connection:save-ai-credentials', payload),
  listAIModels: payload => ipcRenderer.invoke('ai:list-models', payload),
  checkLocalResources: () => ipcRenderer.invoke('ai:check-local-resources'),
  installRecommendedOllamaModel: () => ipcRenderer.invoke('ollama:install-recommended'),
  disconnectAI: () => ipcRenderer.invoke('connection:disconnect-ai'),
  connectSpotify: clientId => ipcRenderer.invoke('connection:connect-spotify', clientId),
  disconnectSpotify: () => ipcRenderer.invoke('connection:disconnect-spotify'),
  connectGoogle: payload => ipcRenderer.invoke('connection:connect-google', payload),
  disconnectGoogle: () => ipcRenderer.invoke('connection:disconnect-google'),
  connectService: payload => ipcRenderer.invoke('connection:connect-service', payload),
  disconnectService: connectorId => ipcRenderer.invoke('connection:disconnect-service', connectorId),
  installBrowserBridge: () => ipcRenderer.invoke('connection:install-browser'),
  nativeStatus: () => ipcRenderer.invoke('native:status'),
  nativeRequest: (method, params) => ipcRenderer.invoke('native:request', { method, params }),
  requestVoicePermissions: () => ipcRenderer.invoke('permissions:request-voice'),
  openVoicePrivacySettings: kind => ipcRenderer.invoke('permissions:open-settings', kind),
  openDictationSettings: () => ipcRenderer.invoke('speech:open-dictation-settings'),
  toggleSpeech: () => ipcRenderer.invoke('speech:toggle'),
  newConversation: privateMode => ipcRenderer.invoke('conversation:new', privateMode),
  openConversation: id => ipcRenderer.invoke('conversation:open', id),
  renameConversation: (id, title) => ipcRenderer.invoke('conversation:rename', { id, title }),
  deleteConversation: id => ipcRenderer.invoke('conversation:delete', id),
  chooseAttachments: privateMode => ipcRenderer.invoke('attachment:choose', { privateMode }),
  removeAttachment: id => ipcRenderer.invoke('attachment:remove', { id }),
  approveAttachmentCloud: ids => ipcRenderer.invoke('attachment:approve-cloud', ids),
  whisperStatus: () => ipcRenderer.invoke('whisper:status'),
  installWhisperBinary: () => ipcRenderer.invoke('whisper:install-binary'),
  installWhisperModel: name => ipcRenderer.invoke('whisper:install', name),
  removeWhisperModel: name => ipcRenderer.invoke('whisper:remove', name),
  runDiagnostics: () => ipcRenderer.invoke('diagnostics:run'),
  exportDiagnostics: () => ipcRenderer.invoke('diagnostics:export'),
  showMain: () => ipcRenderer.send('window:show-main'),
  hideOrb: () => ipcRenderer.send('window:hide-orb'),
  quitApp: () => ipcRenderer.send('app:quit'),
  collapseOrb: () => ipcRenderer.send('window:collapse-orb'),
  expandOrb: () => ipcRenderer.send('window:expand-orb'),
  activateOrb: () => ipcRenderer.send('orb:activate'),
  moveOrb: payload => ipcRenderer.send('orb:drag', payload),
  onState: callback => ipcRenderer.on('state:changed', (_event, state) => callback(state)),
  onTimer: callback => ipcRenderer.on('timer:tick', (_event, timer) => callback(timer)),
  onFocusInput: callback => ipcRenderer.on('command:focus', () => callback()),
  onSpeechTranscript: callback => ipcRenderer.on('speech:transcript', (_event, payload) => callback(payload)),
  onSpeechState: callback => ipcRenderer.on('speech:state', (_event, payload) => callback(payload)),
  onSpeechError: callback => ipcRenderer.on('speech:error', (_event, message) => callback(message)),
  onAssistantStream: callback => ipcRenderer.on('assistant:stream', (_event, payload) => callback(payload))
  ,onWhisperProgress: callback => ipcRenderer.on('whisper:progress', (_event, payload) => callback(payload))
});
