const http = require('node:http');
const crypto = require('node:crypto');
const base64url = value => Buffer.from(value).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');

const FEATURE_SCOPES = Object.freeze({
  profile: ['User.Read'], mail: ['Mail.Read', 'Mail.ReadWrite', 'Mail.Send'], calendar: ['Calendars.ReadWrite'], files: ['Files.ReadWrite'], people: ['People.Read'], tasks: ['Tasks.ReadWrite']
});

class MicrosoftService {
  constructor({ secretStore, shell, fetchImpl = fetch }) { this.secretStore = secretStore; this.shell = shell; this.fetch = fetchImpl; }
  async connect(clientId, features = ['mail','calendar','files','people','tasks']) {
    const id = String(clientId || '').trim(); if (!/^[0-9a-f-]{36}$/i.test(id)) throw new Error('Enter a Microsoft Entra application client ID.');
    const selected = [...new Set(['profile', ...features.filter(name => FEATURE_SCOPES[name])])]; const scopes = [...new Set(['offline_access', ...selected.flatMap(name => FEATURE_SCOPES[name])])];
    const verifier = base64url(crypto.randomBytes(64)); const challenge = base64url(crypto.createHash('sha256').update(verifier).digest()); const state = base64url(crypto.randomBytes(24)); const callback = await this.#callback(state);
    const url = new URL('https://login.microsoftonline.com/common/oauth2/v2.0/authorize'); url.search = new URLSearchParams({ client_id: id, redirect_uri: callback.redirectURI, response_type: 'code', response_mode: 'query', scope: scopes.join(' '), code_challenge: challenge, code_challenge_method: 'S256', state });
    await this.shell.openExternal(url.toString()); let result; try { result = await callback.promise; } finally { callback.close(); }
    const token = await this.#token(new URLSearchParams({ client_id: id, code: result.code, code_verifier: verifier, grant_type: 'authorization_code', redirect_uri: callback.redirectURI, scope: scopes.join(' ') })); await this.#save(token, id, selected); const profile = await this.request('/me?$select=id,displayName,userPrincipalName'); return { accountLabel: profile.displayName || profile.userPrincipalName, features: selected.filter(value => value !== 'profile'), scopes };
  }
  async #callback(expectedState) { let resolveCallback; let rejectCallback; const promise = new Promise((resolve, reject) => { resolveCallback = resolve; rejectCallback = reject; }); const server = http.createServer((request, response) => { const url = new URL(request.url, 'http://127.0.0.1'); if (url.pathname !== '/callback') return response.writeHead(404).end('Not found'); const error = url.searchParams.get('error'); const code = url.searchParams.get('code'); const state = url.searchParams.get('state'); if (error || !code || state !== expectedState) { response.writeHead(400).end('Microsoft connection failed.'); rejectCallback(new Error(error || 'Microsoft returned an invalid authorization response.')); } else { response.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }).end('<!doctype html><title>Microsoft connected</title><main><h1>Microsoft 365 connected.</h1><p>You can close this tab.</p></main>'); resolveCallback({ code }); } }); await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); }); const port = server.address().port; const timeout = setTimeout(() => rejectCallback(new Error('Microsoft authorization timed out.')), 300_000); return { redirectURI: `http://localhost:${port}/callback`, promise, close: () => { clearTimeout(timeout); server.close(); } }; }
  async #token(parameters) { const response = await this.fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: parameters }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error_description || body.error || `Microsoft token request failed (${response.status}).`); return body; }
  async #save(token, clientId, features) { await this.secretStore.set('microsoft.accessToken', token.access_token); if (token.refresh_token) await this.secretStore.set('microsoft.refreshToken', token.refresh_token); await this.secretStore.set('microsoft.expiresAt', String(Date.now() + Math.max(60, Number(token.expires_in || 3600) - 60) * 1000)); await this.secretStore.set('microsoft.clientId', clientId); await this.secretStore.set('microsoft.features', JSON.stringify(features)); }
  async #accessToken() { const access = await this.secretStore.get('microsoft.accessToken'); const expires = Number(await this.secretStore.get('microsoft.expiresAt') || 0); if (access && expires > Date.now()) return access; const refresh = await this.secretStore.get('microsoft.refreshToken'); const clientId = await this.secretStore.get('microsoft.clientId'); if (!refresh || !clientId) throw new Error('Connect Microsoft 365 first.'); const features = JSON.parse(await this.secretStore.get('microsoft.features') || '[]'); const scopes = [...new Set(['offline_access', ...features.flatMap(name => FEATURE_SCOPES[name] || [])])]; const token = await this.#token(new URLSearchParams({ client_id: clientId, refresh_token: refresh, grant_type: 'refresh_token', scope: scopes.join(' ') })); await this.#save(token, clientId, features); return token.access_token; }
  async request(endpoint, options = {}) { const token = await this.#accessToken(); const response = await this.fetch(`https://graph.microsoft.com/v1.0${endpoint}`, { ...options, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', ...(options.headers || {}) } }); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || `Microsoft Graph request failed (${response.status}).`); return body; }
  searchMail(query) { return this.request(`/me/messages?${new URLSearchParams({ '$search': `\"${query.replace(/\"/g, '')}\"`, '$top': '10', '$select': 'id,subject,from,receivedDateTime,bodyPreview,webLink' })}`, { headers: { ConsistencyLevel: 'eventual' } }).then(value => value.value || []); }
  async listTasks() { const lists = await this.request('/me/todo/lists'); const values = await Promise.all((lists.value || []).slice(0, 10).map(list => this.request(`/me/todo/lists/${list.id}/tasks?$top=30`).then(value => (value.value || []).map(task => ({ ...task, listId: list.id, listName: list.displayName }))))); return values.flat(); }
  async createTask(title, dueDateTime = null) { const lists = await this.request('/me/todo/lists'); const list = (lists.value || [])[0]; if (!list) throw new Error('Microsoft To Do has no task list.'); return this.request(`/me/todo/lists/${list.id}/tasks`, { method: 'POST', body: JSON.stringify({ title, ...(dueDateTime ? { dueDateTime: { dateTime: dueDateTime, timeZone: 'UTC' } } : {}) }) }); }
  disconnect() { for (const key of ['microsoft.accessToken','microsoft.refreshToken','microsoft.expiresAt','microsoft.clientId','microsoft.features']) this.secretStore.remove(key); }
}

module.exports = { MicrosoftService, FEATURE_SCOPES };
